### ISSUE TITLE
Upload from browser directly to S3

### ISSUE THREAD

**Issue by vilterp** [rozap/transform#9]
Using an approach like Brian's here: https://gist.github.com/boldfield/66561b4f875511c053f2
1. Browser =(file size)=> our server
2. our server =(...?)=> S3 API
3. S3 API returns signed URLs
4. our server returns them to the browser; one for each chunk
5. browser =(chunk)=> S3 (PUTs to signed URLs)
6. S3 =(notification)=> SQS => our server
7. our server requests chunk from S3 and starts parsing it into basic table chunks

**Comment by rozap** [comment]
this won't work for a lot of files, because we can't chunk them until they're deserialized into a basic table. 

i think we should maybe aim for simple first, so uploading the whole thing to the extractor. also i worry about having complex logic in the client, as it would make exposing the API super hard down the line. initially it would be ideal to just have a simple `/upload` endpoint that people could post to.
